using UnityEditor;
using UnityEngine;

namespace Barliesque.InspectorTools.Editor
{
	[CustomPropertyDrawer(typeof(OptionalAttribute))]
	public class OptionalAttributeDrawer : DecoratorDrawer
	{
		private const string _label = "(Optional)";
		private const string _labelAutoAssign = "(Auto-assigned if missing)";
		private const string _labelAutoGen = "(Generated if missing)";
		private const string _labelObsolete = "(⚠ Obsolete)";

		override public void OnGUI(Rect position)
		{
			var optionalAtt = (OptionalAttribute)attribute;

			var label = optionalAtt.OptionalAttributeType switch
			{
				OptionalType.Optional => _label,
				OptionalType.AutoAssigned => _labelAutoAssign,
				OptionalType.AutoGenerated => _labelAutoGen,
				OptionalType.Obsolete => _labelObsolete,
				_ => string.Empty
			};

			var style = new GUIStyle(EditorStyles.miniLabel);
			style.normal.textColor = new Color(style.normal.textColor.r, style.normal.textColor.g, style.normal.textColor.b, 0.55f);

			var size = style.CalcSize(new GUIContent(label));
			position.height = EditorGUIUtility.singleLineHeight;
			position.x += EditorGUIUtility.labelWidth - size.x - (EditorGUI.indentLevel * EditorTools.IndentPerLevel);

			EditorGUI.LabelField(position, label, style);
		}

		override public float GetHeight() => 0f;
	}
}