using UnityEngine;

namespace Barliesque.InspectorTools
{
	public enum OptionalType
	{
		/// <summary> The field is optional. </summary>
		Optional,
			
		/// <summary> If the reference is missing, it will be found and assigned at runtime. </summary>
		AutoAssigned,
			
		/// <summary> If the reference is missing, a new object will be created and linked to it at runtime. </summary>
		AutoGenerated,

		/// <summary> The field is obsolete and should be avoided. </summary>
		Obsolete,
	}
	
	public class OptionalAttribute : PropertyAttribute
	{
		public readonly OptionalType OptionalAttributeType;

		public OptionalAttribute()
		{
			OptionalAttributeType = OptionalType.Optional;
		}

		public OptionalAttribute(OptionalType optionalAttributeType)
		{
			OptionalAttributeType = optionalAttributeType;
		}
	}
}